<center><a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a></center>
<pre>
<center><b><h1>Data Mining</b></center>
<center><b><h1>Gohel Neel</b></center>
<center><b><h3>Enrollnment No. : 23010101089</b></center>
<center><b><h3>Date: 13-06-2025</b></center>
<center><b><h1>Lab - 2</b></center>  
<pre>

-------------------------------------------------------------------------------
## Numpy

1) NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing.<br>
2) It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.<br>
3) NumPy is highly optimized and written in C, making it much faster than using regular Python lists for numerical operations.<br>
4) It serves as the foundation for many other Python libraries in data science and machine learning, like pandas, TensorFlow, and scikit-learn.<br>
5) With features like broadcasting, vectorization, and integration with C/C++ code, NumPy allows for cleaner and faster code in numerical computations.<br>



### Step 1. Import the Numpy library

In [2]:
import numpy as np



### Step 2. Create a 1D array of numbers

In [6]:
a1 = np.arange(10)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
a2 = np.arange(10,15)
print(a2)

[10 11 12 13 14]


In [9]:
a3 = np.array([10,15,19])
print(a3)

[10 15 19]


### Step 3. Reshape 1D to 2D Array

In [13]:
arr1 = np.arange(9).reshape(3,3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
arr = np.array([10,15,19,45]).reshape(2,2)
print(arr)

[[10 15]
 [19 45]]


### Step 4. Create a Linspace array

In [20]:
array = np.linspace(1,10)
print(array)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [21]:
array = np.linspace(1,10,num=10)
print(array)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


### Step 5. Create a Random Numbered Array

In [25]:
np.random.rand(10)

array([0.76575763, 0.52863704, 0.9538611 , 0.79939943, 0.5389162 ,
       0.89930694, 0.44440197, 0.80625156, 0.6456252 , 0.89784131])

In [26]:
np.random.rand(3,3)

array([[0.4145526 , 0.4967931 , 0.59839409],
       [0.81678759, 0.50369173, 0.88068095],
       [0.57246132, 0.17102137, 0.98227582]])

### Step 6. Create a Random Integer Array

In [38]:
np.random.randint(1,18,size=9)

array([ 2,  5,  2,  3,  7,  1,  1, 16,  4])

In [41]:
np.random.randint(1,18,size=(3,3))

array([[ 6, 12, 10],
       [12, 14, 12],
       [15,  7,  9]])

### Step 7. Create a 1D Array and get Max,Min,ArgMax,ArgMin

In [50]:
a1 = np.arange(15)
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [51]:
max = np.max(a1)
print(max)

14


In [52]:
min = np.min(a1)
print(min)

0


In [53]:
argmax = np.argmax(a1)
print(argmax)

14


In [54]:
argmin = np.argmin(a1)
print(argmin)

0


### Step 8. Indexing in 1D Array

In [63]:
a1 = np.random.randint(1,20,10)
print(a1)

[18 15 14  4 19 10  1  7  1  2]


In [64]:
a1[4:6]

array([19, 10])

### Step 9. Indexing in 2D Array

In [72]:
a1 = np.random.randint(1,25,size=(5,5))
print(a1)

[[22  5 17  5 23]
 [13  1 23  7 13]
 [14 22 18 10 11]
 [16 17  7 14 20]
 [20  2  8  5 17]]


In [92]:
a1[2]


np.int64(27)

In [74]:
a1[1:3]

array([[13,  1, 23,  7, 13],
       [14, 22, 18, 10, 11]])

In [77]:
# a1[2,3]
a1[3][3]

np.int64(14)

### Step 10. Conditional Selection

In [78]:
a1 = np.random.randint(20,40,10)
print(a1)

[32 24 27 36 29 39 38 34 25 38]


In [84]:
a1[(a1>25)&(a1<35)]

array([32, 27, 29, 34])

### 🔥You did it! 10 exercises down — you're on fire! 🔥

## Pandas



### Step 1. Import the necessary libraries

In [22]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [93]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep="|",index_col="user_id")

### Step 4. See the first 25 entries

In [ ]:
users.head(25)

### Step 5. See the last 10 entries

In [ ]:
users.tail(10)

### Step 6. What is the number of observations in the dataset?

In [103]:
users.shape[0]

943

### Step 7. What is the number of columns in the dataset?

In [104]:
users.shape[1]

4

### Step 8. Print the name of all the columns.

In [105]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [106]:
users.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?

In [ ]:
users.dtypes

### Step 11. Print only the occupation column

In [ ]:
users["occupation"]

### Step 12. How many different occupations are in this dataset?

In [116]:
users["occupation"].nunique()
users["occupation"].unique()

array(['technician', 'other', 'writer', 'executive', 'administrator',
       'student', 'lawyer', 'educator', 'scientist', 'entertainment',
       'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
       'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
      dtype=object)

### Step 13. What is the most frequent occupation?

In [123]:
users["occupation"].value_counts()

'student'

In [ ]:
users["occupation"].value_counts().head(1)

In [125]:
users["occupation"].value_counts().idxmax()

'student'

### Step 14. Summarize the DataFrame.

In [ ]:
users.describe()

### Step 15. Summarize all the columns

In [ ]:
users.describe(include="all")

### Step 16. Summarize only the occupation column

In [ ]:
users["occupation"].describe()

### Step 17. What is the mean age of users?

In [122]:
print(users["age"].mean())

34.05196182396607


### Step 18. What is the age with least occurrence?

In [ ]:
users["age"].value_counts().tail()

### You're not just learning, you're mastering it. Keep aiming higher! 🚀